package com.zh.business.pojo;

import java.util.Date;

public class Shipping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_name
     *
     * @mbg.generated
     */
    private String receiveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_phone
     *
     * @mbg.generated
     */
    private String receivePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_mobile
     *
     * @mbg.generated
     */
    private String receiveMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_province
     *
     * @mbg.generated
     */
    private String receiveProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_city
     *
     * @mbg.generated
     */
    private String receiveCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_district
     *
     * @mbg.generated
     */
    private String receiveDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_address
     *
     * @mbg.generated
     */
    private String receiveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.receive_zip
     *
     * @mbg.generated
     */
    private String receiveZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shipping.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.id
     *
     * @return the value of neuedu_shipping.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.id
     *
     * @param id the value for neuedu_shipping.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.user_id
     *
     * @return the value of neuedu_shipping.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.user_id
     *
     * @param userId the value for neuedu_shipping.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_name
     *
     * @return the value of neuedu_shipping.receive_name
     *
     * @mbg.generated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_name
     *
     * @param receiveName the value for neuedu_shipping.receive_name
     *
     * @mbg.generated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_phone
     *
     * @return the value of neuedu_shipping.receive_phone
     *
     * @mbg.generated
     */
    public String getReceivePhone() {
        return receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_phone
     *
     * @param receivePhone the value for neuedu_shipping.receive_phone
     *
     * @mbg.generated
     */
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone == null ? null : receivePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_mobile
     *
     * @return the value of neuedu_shipping.receive_mobile
     *
     * @mbg.generated
     */
    public String getReceiveMobile() {
        return receiveMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_mobile
     *
     * @param receiveMobile the value for neuedu_shipping.receive_mobile
     *
     * @mbg.generated
     */
    public void setReceiveMobile(String receiveMobile) {
        this.receiveMobile = receiveMobile == null ? null : receiveMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_province
     *
     * @return the value of neuedu_shipping.receive_province
     *
     * @mbg.generated
     */
    public String getReceiveProvince() {
        return receiveProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_province
     *
     * @param receiveProvince the value for neuedu_shipping.receive_province
     *
     * @mbg.generated
     */
    public void setReceiveProvince(String receiveProvince) {
        this.receiveProvince = receiveProvince == null ? null : receiveProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_city
     *
     * @return the value of neuedu_shipping.receive_city
     *
     * @mbg.generated
     */
    public String getReceiveCity() {
        return receiveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_city
     *
     * @param receiveCity the value for neuedu_shipping.receive_city
     *
     * @mbg.generated
     */
    public void setReceiveCity(String receiveCity) {
        this.receiveCity = receiveCity == null ? null : receiveCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_district
     *
     * @return the value of neuedu_shipping.receive_district
     *
     * @mbg.generated
     */
    public String getReceiveDistrict() {
        return receiveDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_district
     *
     * @param receiveDistrict the value for neuedu_shipping.receive_district
     *
     * @mbg.generated
     */
    public void setReceiveDistrict(String receiveDistrict) {
        this.receiveDistrict = receiveDistrict == null ? null : receiveDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_address
     *
     * @return the value of neuedu_shipping.receive_address
     *
     * @mbg.generated
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_address
     *
     * @param receiveAddress the value for neuedu_shipping.receive_address
     *
     * @mbg.generated
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.receive_zip
     *
     * @return the value of neuedu_shipping.receive_zip
     *
     * @mbg.generated
     */
    public String getReceiveZip() {
        return receiveZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.receive_zip
     *
     * @param receiveZip the value for neuedu_shipping.receive_zip
     *
     * @mbg.generated
     */
    public void setReceiveZip(String receiveZip) {
        this.receiveZip = receiveZip == null ? null : receiveZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.create_time
     *
     * @return the value of neuedu_shipping.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.create_time
     *
     * @param createTime the value for neuedu_shipping.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_shipping.update_time
     *
     * @return the value of neuedu_shipping.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_shipping.update_time
     *
     * @param updateTime the value for neuedu_shipping.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}